{
  "openapi": "3.0.0",
  "info": {
    "title": "Kenzie Buster API",
    "description": "Está documentação visa esclarecer o uso dos endpoints da API Kenzie buster.",
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://entrega-kenzie-buster.herokuapp.com/api/vi",
      "description": "API de produção"
    },
    {
      "url": "http://localhost:3000/api/v1",
      "description": "API de desenvolvimento"
    }
  ],
  "paths": {
    "/users/register": {
      "post": {
        "summary": "Registro de usuário",
        "description": "Rota para registro de usuários admins e não admins. <br/><br/>Somente usuários admin podem criar outros admins.",
        "tags": ["User"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserRegisterRequest"
              },
              "examples": {
                "kenzie": {
                  "value": {
                    "name": "kenzie",
                    "email": "kenzie@mail.com",
                    "password": "kenzinho",
                    "isAdmin": false
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Este erro ocorre quando algum campo necessário não é enviado no body da requisição, ou o tipo de dado de algum campo é diferente do esperado, veja o schema.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserRegisterRequest"
                },
                "examples": {
                  "nenhum_campo_enviado": {
                    "value": {
                      "error": [
                        "name is a required field",
                        "email is a required field",
                        "password is a required field"
                      ]
                    }
                  },
                  "name_nao_enviado": {
                    "value": {
                      "error": ["name is a required field"]
                    }
                  },
                  "email_nao_enviado": {
                    "value": {
                      "error": ["email is a required field"]
                    }
                  },
                  "password_nao_enviado": {
                    "value": {
                      "error": ["password is a required field"]
                    }
                  },
                  "email_enviado_como_array": {
                    "value": {
                      "error": [
                        "email must be a `string` type, but the final value was: `[\n  \"\\\"kenzie@mail.com\\\"\"\n]`."
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Este erro ocorre quando se tenta criar um usuário como admin sem token válido, ou com token de usuário não admin",
            "content": {
              "application/json": {
                "examples": {
                  "sem_token_valido": {
                    "value": {
                      "error": "Missing authorization token."
                    }
                  },
                  "sem_permissao_admin": {
                    "value": {
                      "error": "Missing admin permission."
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email já utilizado",
            "content": {
              "application/json": {
                "examples": {
                  "email_ja_utilizado": {
                    "value": {
                      "error": "Key (email)=(kenzie@kenzie.com) already exists"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "summary": "Login de usuários",
        "description": "Rota para login de usuários admins e não admins",
        "tags": ["User"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserLoginRequest"
              },
              "examples": {
                "kenzie": {
                  "value": {
                    "email": "kenzie@mail.com",
                    "password": "kenzinho"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Este erro ocorre quando algum campo necessário não é enviado no body da requisição, quando as credenciais são inválidas ou o tipo de dado de algum campo é diferente do esperado, veja o schema.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserLoginRequest"
                },
                "examples": {
                  "credenciais_invalidas": {
                    "value": {
                      "message": "Invalid email or password"
                    }
                  },
                  "credenciais_nao_enviadas": {
                    "value": {
                      "error": [
                        "email is a required field",
                        "password is a required field"
                      ]
                    }
                  },
                  "email_enviado_como_array": {
                    "value": {
                      "error": [
                        "email must be a `string` type, but the final value was: `[\n  \"\\\"kenzie@mail.com\\\"\"\n]`."
                      ]
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "Login realizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserLoginResponse"
                },
                "examples": {
                  "kenzie": {
                    "value": {
                      "user": {
                        "isAdmin": false,
                        "email": "kenzie@kenzie.com",
                        "name": "Kenzie",
                        "id": "add14f8e-c3e9-4621-ad13-652ef8c85824"
                      },
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjpmYWxzZSwiZW1haWwiOiJrZW56aWVAa2VuemllLmNvbSIsIm5hbWUiOiJLZW56aWUiLCJpZCI6ImFkZDE0ZjhlLWMzZTktNDYyMS1hZDEzLTY1MmVmOGM4NTgyNCIsImlhdCI6MTY1NDE3MTM5OSwiZXhwIjoxNjU0MTc0OTk5fQ.ReiHL-qtAIEVGdS714O8U7Sn5iEE9wFmFZkhCj0_PtQ"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserLoginRequest": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "UserLoginResponse": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "content": {
              "isAdmin": {
                "type": "boolean"
              },
              "email": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "id": {
                "type": "string"
              }
            }
          },
          "token": {
            "type": "string"
          }
        }
      },
      "UserRegisterRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "isAdmin": {
            "type": "boolean"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
